"""add classify debug info

Revision ID: 2c7a76296e9d
Revises: 420aa3a0f72c
Create Date: 2026-01-12 21:56:23.068395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7a76296e9d'
down_revision: Union[str, Sequence[str], None] = '420aa3a0f72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('needs_review', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('runner_up_confidence', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'margin')
    op.drop_column('articles', 'runner_up_confidence')
    op.drop_column('articles', 'reason')
    op.drop_column('articles', 'needs_review')
    # ### end Alembic commands ###
