"""remove description and raw columns

Revision ID: 420aa3a0f72c
Revises: dd887efa8901
Create Date: 2026-01-11 09:10:08.130080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '420aa3a0f72c'
down_revision: Union[str, Sequence[str], None] = 'dd887efa8901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'description')
    op.drop_column('articles', 'raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
